### ISSUE TITLE
This code, written by AI and leaked, causes problems in the layout.

### ISSUE THREAD

**Issue by javiertringol** [opentibiabr/otclient#1366]
### Priority

Critical

### Area

- [x] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

This code https://github.com/mehah/otclient/commit/89756963531ba73b2613976183093abf8f750c70 https://github.com/mehah/otclient/pull/1310, written by AI and leaked, causes problems in the layout.
### "feat: game analysers and fix: cooldown bars " by libergod 

 ![Image](https://github.com/user-attachments/assets/6740a9b3-256d-4acc-8dcf-4d02e3ca1697)

<img width="283" height="304" alt="Image" src="https://github.com/user-attachments/assets/9415ebdc-9173-4ee9-8fa3-b7b247c1e8d2" />

# and broke the WASD controls

**Comment by libergod** [comment]
First, thanks for bringing this to our attention, but HEY! Take care with what you say in others' contributions because first, you did nothing yet and second, this wasn't a problem introduced with my modifications. In fact, the minimap.otui hadn't received updates/improvements since 2024. 

Anyway, here is the solution that you couldn't identify, even though it is really simple. 

BTW, this is not the first time you come to share shity comments on others' repo/pr.

Also, WASD was fixed by this PR #1374, which highlights your lack of research.

<img width="1902" height="898" alt="Image" src="https://github.com/user-attachments/assets/f192389f-c661-4c5c-9fbc-61e1c4afa347" />

**Comment by javiertringol** [comment]
Please stop using AI to fix code made with AI.

Think a little , if the error comes from here https://github.com/mehah/otclient/pull/1310/files
look at what you modified.
Here I see a change that affects the entire layout in the most unnecessary way I've ever seen.

Your PR doesn't solve anything , it only fixes a few specific UI issues.
But, AS I SAID BEFORE, DATA/STYLE AFFECTS THE ENTIRE LAYOUT.



<img width="424" height="267" alt="Image" src="https://github.com/user-attachments/assets/c7e4ded3-7ccd-4837-9c1c-0ef743c2ea74" />


-
About the WASD issue , it broke in your modification to game_interface.
That issue has been open for 5 days, and the PR you mentioned , which supposedly fixes it , has only been around for 3 days.
That's not a real solution. It's just more AI-generated code trying to fix a bug caused by AI.

STOP USING AI.
