### ISSUE TITLE
minimap bug

### ISSUE THREAD

**Issue by patrykq112** [opentibiabr/otclient#419]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

I found such a bug in the latest source, see the gif:
![minimap bug](https://user-images.githubusercontent.com/16617982/219073939-b6caff8f-37f1-478f-9440-0f061994e542.gif)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
I couldn't reproduce.

**Comment by themaoci** [comment]
i also couldn't reproduce it

**Comment by kokekanon** [comment]
Sorry for commenting on an issue that is closed, but the same bug appeared in version 3.0.2
, I have not been able to reproduce it again
but
I died, I appeared in center and those letters appeared on the minimap
It only happened in the temple, if he entered a portal. the area of the portal did not appear the bug. but if I returned to the area those letters would appear

I logged out and it was fixed

![Screenshot_2](https://user-images.githubusercontent.com/114332266/226516302-8c9cec5d-c7cf-4a33-8e9b-1cea9af02f3f.png)

![asdasdxzxzccaslhd](https://user-images.githubusercontent.com/114332266/226516419-314205b6-0b5d-4868-a7de-6504b025e086.gif)

I noticed that the minimap didn't load
just a visual bug
@mehah I tag you, because it seems that the notification is not sent

**Comment by patrykq112** [comment]
> Sorry for commenting on an issue that is closed, but the same bug appeared in version 3.0.2 , I have not been able to reproduce it again but I died, I appeared in center and those letters appeared on the minimap It only happened in the temple, if he entered a portal. the area of the portal did not appear the bug. but if I returned to the area those letters would appear
> 
> I logged out and it was fixed
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/114332266/226516302-8c9cec5d-c7cf-4a33-8e9b-1cea9af02f3f.png)
> 
> ![asdasdxzxzccaslhd](https://user-images.githubusercontent.com/114332266/226516419-314205b6-0b5d-4868-a7de-6504b025e086.gif) [ ![asdasdxzxzccaslhd](https://user-images.githubusercontent.com/114332266/226516419-314205b6-0b5d-4868-a7de-6504b025e086.gif) ](https://user-images.githubusercontent.com/114332266/226516419-314205b6-0b5d-4868-a7de-6504b025e086.gif) [ ](https://user-images.githubusercontent.com/114332266/226516419-314205b6-0b5d-4868-a7de-6504b025e086.gif)
> 
> I noticed that the minimap didn't load just a visual bug @mehah I tag you, because it seems that the notification is not sent

I still have this bug, but at random times, I don't know how to reproduce it

**Comment by mehah** [comment]
I'm going to reformulate some things to see if this solves it.
