### ISSUE TITLE
Protocol 13.16

### ISSUE THREAD

**Issue by GibionMillak** [opentibiabr/otclient#550]
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

I'm using Canary OT 13.16, I put the "assets" folder of the 13.16 client inside "data/things/1316", and even then I get this error when entering.

 
![error](https://github.com/mehah/otclient/assets/62446430/bc4726b5-3f80-4561-b222-6bf01cbe70a2)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
https://docs.opentibiabr.com/projects/canary/infrastructure/windows/basic/xampp/basic-windows-canary-otservbr-global-+-xampp-+-login-server

ip: 127.0.0.1
port: 80

**Comment by majestyotbr** [comment]
Open otclient terminal and post the log.

**Comment by majestyotbr** [comment]
The problem is not in the otclient, if you are using this [MyAAC](https://github.com/opentibiabr/myaac) download it again and reinstall. It was just the missing column "ismain" that MyAAC need to add in the players table of Canary database and it was fixed here: https://github.com/opentibiabr/myaac/commit/54ad2b8c0174e764eedd80acb79e6fd452088632.
Do it and the login will work.
Next time, use the [OpenTibiaBR Discord](https://discord.gg/gvTj5sh9Mp) or [OTClient Redemption Discord](https://discord.gg/HZN8yJJSyC) to ask for support.

**Comment by gibionmillak** [comment]
I already did that, it was the first thing I did, and the error remains the same. Anyway, thanks for the feedback.

**Comment by gibionmillak** [comment]
> The problem is not in the otclient, if you are using this [MyAAC](https://github.com/opentibiabr/myaac) download it again and reinstall. It was just the missing column "ismain" that MyAAC need to add in the players table of Canary database and it was fixed here: [opentibiabr/myaac@54ad2b8](https://github.com/opentibiabr/myaac/commit/54ad2b8c0174e764eedd80acb79e6fd452088632). Do it and the login will work. Next time, use the [OpenTibiaBR Discord](https://discord.gg/gvTj5sh9Mp) or [OTClient Redemption Discord](https://discord.gg/HZN8yJJSyC) to ask for support.

I already did that, it was the first thing I did, and the error remains the same. Anyway, thanks for the feedback.
